### PR TITLE
Create Turkish strings.xml

### PR DESCRIPTION
**Pull request by Fatih-BaKeR**
Hello dear developer. If you use the translation, I can see my mistakes and do better. Please do not combine it with the translation on the translation site, just use this. Thanks. Have a healthy day.

### CODE REVIEW

**Comment by sunilpaulmathew** [comment]
@Fatih-BaKeR 
Thanks a lot for your support.
Is this Turkish from Turkey or Cyprus? Either way, it needs to be moved to a separate folder. I'll do it for you. Anyway, I have to upload it to POEditor once it is merged to source for the future contributors. Also, do you want a test build?

**Comment by Fatih-BaKeR** [comment]
> @Fatih-BaKeR
> Thanks a lot for your support.
> Is this Turkish from Turkey or Cyprus? Either way, it needs to be moved to a separate folder. I'll do it for you. Anyway, I have to upload it to POEditor once it is merged to source for the future contributors. Also, do you want a test build?

 Thank you too. I'm from turkey. I apologize if I made a mistake. I'm not new to translation but still don't understand github :(. Yes, test build would be great. Thanks again.

**Comment by sunilpaulmathew** [comment]
> translation on the

Nice, and here you go.
https://www.dropbox.com/s/9tse8288dvs6f3d/com.smartpack.kernelmanager.apk?dl=0
Also, I can replace the entire Turkish strings in POEditor with your version so that it will be perfect.

**Comment by Fatih-BaKeR** [comment]
> > translation on the
> 
> Nice, and here you go.
> https://www.dropbox.com/s/9tse8288dvs6f3d/com.smartpack.kernelmanager.apk?dl=0
> Also, I can replace the entire Turkish strings in POEditor with your version so that it will be perfect.



> > translation on the
> 
> Nice, and here you go.
> https://www.dropbox.com/s/9tse8288dvs6f3d/com.smartpack.kernelmanager.apk?dl=0
> Also, I can replace the entire Turkish strings in POEditor with your version so that it will be perfect.

I want to test it for a few days and send a pull request again if there is an error. Thanks much for your support and test build.

**Comment by sunilpaulmathew** [comment]
> test it for a few day

Cool. I'll push the initial version to GitHub and POEditor now so that you can easily update it.
Again, thank you so much for your support.

**Comment by sunilpaulmathew** [comment]
@Fatih-BaKeR 
Done. So, please work on this [file](https://github.com/SmartPack/SmartPack-Kernel-Manager/blob/master/app/src/main/res/values-tr-rTR/strings.xml) or [POEditor](https://poeditor.com/join/project?hash=qWFlVfAlp5) (now it's completely your version), whichever you prefer.
Have a nice evening.

**Comment by Fatih-BaKeR** [comment]
> @Fatih-BaKeR
> Done. So, please work on this [file](https://github.com/SmartPack/SmartPack-Kernel-Manager/blob/master/app/src/main/res/values-tr-rTR/strings.xml) or [POEditor](https://poeditor.com/join/project?hash=qWFlVfAlp5) (now it's completely your version), whichever you prefer.
> Have a nice evening.

Hi again. I have one more request. Can you add the last english words? I added it, but when I try to compile it, the newly added words (eg update part) disappear. Sorry for that. Thanks much.

**Comment by sunilpaulmathew** [comment]
> > @Fatih-BaKeR
> > Done. So, please work on this [file](https://github.com/SmartPack/SmartPack-Kernel-Manager/blob/master/app/src/main/res/values-tr-rTR/strings.xml) or [POEditor](https://poeditor.com/join/project?hash=qWFlVfAlp5) (now it's completely your version), whichever you prefer.
> > Have a nice evening.
> 
> Hi again. I have one more request. Can you add the last english words? I added it, but when I try to compile it, the newly added words (eg update part) disappear. Sorry for that. Thanks much.

These are the newly added strings. If you send me the translations here, I shall manage it.

    <string name="doze">Force Doze</string>
    <string name="doze_summary">Enable doze mode to prevents certain tasks from running if your device is in idle state.</string>
    <string name="selinux">SELinux</string>
    <string name="selinux_summary">Set SELinux state</string>
    <string name="selinux_permissive">Permissive</string>
    <string name="selinux_enforcing">Enforcing</string>

    <string name="on_boot_swipe_drag_message">You can swipe left or right to remove a command (not a profile or script)!</string>
    <string name="swipe_message">Sorry! You can\'t swipe out a %s.</string>
    <string name="drag_message">Sorry! You can\'t drag a %s into different position.</string>

    <string name="update_available">New update available!\nv%s</string>
    <string name="get_it">Get It</string>
    <string name="download_failed">It seems like the download is failed, or a corrupted file is downloaded!</string>
    <string name="updated_dialog">Congrats! You\'ve already got an up-to-date version of SmartPack-Kernel Manager!</string>
    <string name="auto_update_check">Auto Update Check</string>
    <string name="check_update">Check for Updates</string>
    <string name="check_update_summary">Check for new versions of SmartPack-Kernel Manager</string>

    <string name="fdroid">F-Droid</string>
    <string name="fdroid_summary">Visit F-Droid page</string>

**Comment by Fatih-BaKeR** [comment]
> > > @Fatih-BaKeR
> > > Done. So, please work on this [file](https://github.com/SmartPack/SmartPack-Kernel-Manager/blob/master/app/src/main/res/values-tr-rTR/strings.xml) or [POEditor](https://poeditor.com/join/project?hash=qWFlVfAlp5) (now it's completely your version), whichever you prefer.
> > > Have a nice evening.
> > 
> > 
> > Hi again. I have one more request. Can you add the last english words? I added it, but when I try to compile it, the newly added words (eg update part) disappear. Sorry for that. Thanks much.
> 
> These are the newly added strings. If you send me the translations here, I shall manage it.
> 
> ```
> <string name="doze">Force Doze</string>
> <string name="doze_summary">Enable doze mode to prevents certain tasks from running if your device is in idle state.</string>
> <string name="selinux">SELinux</string>
> <string name="selinux_summary">Set SELinux state</string>
> <string name="selinux_permissive">Permissive</string>
> <string name="selinux_enforcing">Enforcing</string>
> 
> <string name="on_boot_swipe_drag_message">You can swipe left or right to remove a command (not a profile or script)!</string>
> <string name="swipe_message">Sorry! You can\'t swipe out a %s.</string>
> <string name="drag_message">Sorry! You can\'t drag a %s into different position.</string>
> 
> <string name="update_available">New update available!\nv%s</string>
> <string name="get_it">Get It</string>
> <string name="download_failed">It seems like the download is failed, or a corrupted file is downloaded!</string>
> <string name="updated_dialog">Congrats! You\'ve already got an up-to-date version of SmartPack-Kernel Manager!</string>
> <string name="auto_update_check">Auto Update Check</string>
> <string name="check_update">Check for Updates</string>
> <string name="check_update_summary">Check for new versions of SmartPack-Kernel Manager</string>
> 
> <string name="fdroid">F-Droid</string>
> <string name="fdroid_summary">Visit F-Droid page</string>
> ```

Turkish translation is here, thanks much.

<string name="doze">Doze Modunu Zorla</string>
<string name="doze_summary">Cihazınız boştayken belirli görevlerin çalışmasını önlemek için doze modunu etkinleştirin.</string>
<string name="selinux">SELinux</string>
<string name="selinux_summary">SELinux durumunu ayarla</string>
<string name="selinux_permissive">Permissive</string>
<string name="selinux_enforcing">Enforcing</string>

<string name="on_boot_swipe_drag_message">Bir komutu (bir profili veya komut dosyasını değil) kaldırmak için sola veya sağa kaydırabilirsiniz!</string>
<string name="swipe_message">Üzgünüz! Bir %s kaydırılamaz.</string>
<string name="drag_message">Üzgünüz! Bir %s farklı bir konuma kaydırılamaz.</string>

<string name="update_available">Yeni güncelleme mevcut!\nv%s</string>
<string name="get_it">Anladım</string>
<string name="download_failed">Görünüşe göre indirme başarısız oldu veya bozuk bir dosya indirildi!</string>
<string name="updated_dialog">"Tebrikler! SmartPack-Kernel Manager'ın güncel bir sürümüne zaten sahipsiniz!"</string>
<string name="auto_update_check">Otomatik Güncelleme Kontrolü</string>
<string name="check_update">Güncellemeleri Kontrol Et</string>
<string name="check_update_summary">"SmartPack-Kernel Manager'ın yeni sürümlerini kontrol edin"</string>

<string name="fdroid">F-Droid</string>
<string name="fdroid_summary">F-Droid sayfasını ziyaret edin</string>

**Comment by Fatih-BaKeR** [comment]
> > > @Fatih-BaKeR
> > > Done. So, please work on this [file](https://github.com/SmartPack/SmartPack-Kernel-Manager/blob/master/app/src/main/res/values-tr-rTR/strings.xml) or [POEditor](https://poeditor.com/join/project?hash=qWFlVfAlp5) (now it's completely your version), whichever you prefer.
> > > Have a nice evening.
> > 
> > 
> > Hi again. I have one more request. Can you add the last english words? I added it, but when I try to compile it, the newly added words (eg update part) disappear. Sorry for that. Thanks much.
> 
> These are the newly added strings. If you send me the translations here, I shall manage it.
> 
> ```
> <string name="doze">Force Doze</string>
> <string name="doze_summary">Enable doze mode to prevents certain tasks from running if your device is in idle state.</string>
> <string name="selinux">SELinux</string>
> <string name="selinux_summary">Set SELinux state</string>
> <string name="selinux_permissive">Permissive</string>
> <string name="selinux_enforcing">Enforcing</string>
> 
> <string name="on_boot_swipe_drag_message">You can swipe left or right to remove a command (not a profile or script)!</string>
> <string name="swipe_message">Sorry! You can\'t swipe out a %s.</string>
> <string name="drag_message">Sorry! You can\'t drag a %s into different position.</string>
> 
> <string name="update_available">New update available!\nv%s</string>
> <string name="get_it">Get It</string>
> <string name="download_failed">It seems like the download is failed, or a corrupted file is downloaded!</string>
> <string name="updated_dialog">Congrats! You\'ve already got an up-to-date version of SmartPack-Kernel Manager!</string>
> <string name="auto_update_check">Auto Update Check</string>
> <string name="check_update">Check for Updates</string>
> <string name="check_update_summary">Check for new versions of SmartPack-Kernel Manager</string>
> 
> <string name="fdroid">F-Droid</string>
> <string name="fdroid_summary">Visit F-Droid page</string>
> ```

Turkish translation is here, sorry I couldn't add it here.

https://justpaste.it/edit/41234055/d10q1zb2d7nv7m4f

**Comment by sunilpaulmathew** [comment]
> > > > @Fatih-BaKeR
> > > > Done. So, please work on this [file](https://github.com/SmartPack/SmartPack-Kernel-Manager/blob/master/app/src/main/res/values-tr-rTR/strings.xml) or [POEditor](https://poeditor.com/join/project?hash=qWFlVfAlp5) (now it's completely your version), whichever you prefer.
> > > > Have a nice evening.
> > > 
> > > 
> > > Hi again. I have one more request. Can you add the last english words? I added it, but when I try to compile it, the newly added words (eg update part) disappear. Sorry for that. Thanks much.
> > 
> > 
> > These are the newly added strings. If you send me the translations here, I shall manage it.
> > ```
> > <string name="doze">Force Doze</string>
> > <string name="doze_summary">Enable doze mode to prevents certain tasks from running if your device is in idle state.</string>
> > <string name="selinux">SELinux</string>
> > <string name="selinux_summary">Set SELinux state</string>
> > <string name="selinux_permissive">Permissive</string>
> > <string name="selinux_enforcing">Enforcing</string>
> > 
> > <string name="on_boot_swipe_drag_message">You can swipe left or right to remove a command (not a profile or script)!</string>
> > <string name="swipe_message">Sorry! You can\'t swipe out a %s.</string>
> > <string name="drag_message">Sorry! You can\'t drag a %s into different position.</string>
> > 
> > <string name="update_available">New update available!\nv%s</string>
> > <string name="get_it">Get It</string>
> > <string name="download_failed">It seems like the download is failed, or a corrupted file is downloaded!</string>
> > <string name="updated_dialog">Congrats! You\'ve already got an up-to-date version of SmartPack-Kernel Manager!</string>
> > <string name="auto_update_check">Auto Update Check</string>
> > <string name="check_update">Check for Updates</string>
> > <string name="check_update_summary">Check for new versions of SmartPack-Kernel Manager</string>
> > 
> > <string name="fdroid">F-Droid</string>
> > <string name="fdroid_summary">Visit F-Droid page</string>
> > ```
> 
> Turkish translation is here, sorry I couldn't add it here.
> 
> https://justpaste.it/edit/41234055/d10q1zb2d7nv7m4f

Included in https://github.com/SmartPack/SmartPack-Kernel-Manager/commit/f78ad4e9c54f6c78e28196a4f9150d5b462212ad
Closing this PR too. But, feel free to re-open it, if you want to make more changes. Also, I shall create a new release soon so that more people will be able to test. Thanks a lot for your contribution.

**Pull request closed without merging**
